---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🏷️ Python Project Dynamic Versioning"

outputs:
  DYNAMIC_VERSION:
    description: "Set true if pyproject.toml configured for DYNAMIC versioning"
    value: ${{ steps.project-versioning.outputs.dynamic }}

runs:
  using: "composite"
  steps:
    - name: "Check project for dynamic versioning"
      id: project-versioning
      shell: bash
      run: |
        # Check project for dynamic versioning
        if $(grep -q -E "^dynamic = \[ \"version\" \]$" pyproject.toml); then
          echo "Dynamic pyproject.toml versioning: TRUE"
          echo "dynamic=true" >> $GITHUB_OUTPUT
        else
          echo "Dynamic pyproject.toml versioning: FALSE"
          echo "dynamic_version=false" >> $GITHUB_OUTPUT
        fi
