---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🛠️ Check/Verify GitHub Secrets"
description: "Checks/verifies access to required secrets"
# These need to be setup at either the ORG or REPO level
# (i.e. available to workflows in this repository)
# e.g. PyPI API Keys required for package publishing
# (when trusted publishing has not yet been setup)

inputs:
  PYPI_DEVELOPMENT:
    description: "Token needed to publish packages to: test.pypi.org"
    required: true
  PYPI_PRODUCTION:
    description: "Token needed to publish packages to: pypi.org"
    required: true
  ONE_PASSWORD_DEVELOPMENT:
    description: "Test service account for 1Password vault access"
    required: true

outputs:
  VALID:
    description: "Returns true if the labels exist"
    value: ${{ steps.secrets.outputs.present }}

runs:
  using: "composite"
  steps:
    - id: secrets
      env:
        PYPI_DEVELOPMENT: ${{ inputs.pypi_development }}
        PYPI_PRODUCTION: ${{ inputs.pypi_production }}
        ONE_PASSWORD_DEVELOPMENT: ${{ inputs.one_password_development }}

      shell: bash
      run: |
        # Check for mandatory secrets/variables

        #SHELLCODESTART

        # Allows for testing from a local shell
        if [ -z "$GITHUB_OUTPUT" ]; then
          echo "Running from a shell, NOT workflow"
          export GITHUB_OUTPUT="/dev/null"
          export GITHUB_ENV="/dev/null"
        fi

        # Initial assumption is that secrets do NOT exist
        PRESENT="false"

        # Define the secrets we need to verify

        # Check/validate mandatory secrets/variables

        # File format is: [SECRET NAME] [SHA1SUM]
        TMPFILE=$(mktemp -p /tmp --suffix "-secrets.txt")
        cat << EOF > "$TMPFILE"
        PYPI_DEVELOPMENT 19fc83e3c621347f85573fa0ea9dffff6542d3e3
        PYPI_PRODUCTION dcfaee96a60c6f8e44c870ed7058fe55d8b11fc6
        ONE_PASSWORD_DEVELOPMENT 11f6fc3cd4f537b1aa54d5d924a129384777de2a
        EOF

        # Iterate over secrets and validate checksums against those stored in GitHub
        ERRORS="false"
        while read -r LINE; do
          STRING_ARRAY=($LINE)
          SECRET=${STRING_ARRAY[0]}
          EXPECTED=${STRING_ARRAY[1]}
          if [ "$SECRET" == "PYPI_DEVELOPMENT" ]; then
            CHECKSUM=$(echo ${{ env.PYPI_DEVELOPMENT }} | sha1sum | awk '{print $1}')
          elif [ "$SECRET" == "PYPI_PRODUCTION" ]; then
            CHECKSUM=$(echo ${{ env.PYPI_PRODUCTION }} | sha1sum | awk '{print $1}')
          elif [ "$SECRET" == "ONE_PASSWORD_DEVELOPMENT" ]; then
            CHECKSUM=$(echo ${{ env.ONE_PASSWORD_DEVELOPMENT }} | sha1sum | awk '{print $1}')
          else
            echo "Unexpected secret $SECRET was NOT found in validation table"
            echo "Error: the validation workflow may need updating"
            ERRORS="true"
          fi

          if [ "$EXPECTED" == "$CHECKSUM" ]; then
            echo "Successfully validated secret: $SECRET $CHECKSUM"
          else
            echo "Error: checksum validation failed for $SECRET"
            echo "Got: $CHECKSUM Expected: $EXPECTED"
            if [ "$CHECKSUM" == "adc83b19e793491b1c6ea0fd8b46cd9f32e592fc" ];then
              echo "Note: this SHA1 value represents a null/empty string"
            fi
            ERRORS="true"
          fi
        done < "$TMPFILE"

        if [ "$ERRORS" == true ]; then
          exit 1
        fi

        #SHELLCODEEND
