---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🐍 Get Python Project Version"
description: "Returns the version of the Python Project"

outputs:
  PYTHON_PROJECT_VERSION:
    description: "The version of the Python project from pyproject.toml or setup.py"
    value: ${{ steps.python-project-version.outputs.python_project_version }}

runs:
  using: "composite"
  steps:
    - name: "Capture Python project version"
      id: python-project-version
      shell: bash
      run: |
        # Capture Python project version

        #SHELLCODESTART

        # Allows for testing from a local shell
        if [ -z "$GITHUB_OUTPUT" ]; then
          echo "Running from a shell, NOT workflow"
          export GITHUB_OUTPUT="/dev/null"
          export GITHUB_ENV="/dev/null"
        fi

        if [ -f pyproject.toml ]; then
          echo "Extracting project version from pyproject.toml."
          PYTHON_PROJECT_VERSION=$(pdm show --version)

        elif [ -f setup.py ]; then
          echo "Extracting project version from setup.py."
          pip install -q --upgrade pip
          pip install --upgrade -q setuptools
          PYTHON_PROJECT_VERSION=$(python ./setup.py --version)

        else
          echo "Error: neither pyproject.toml not setup.py was found"; exit 1
        fi

        echo "PYTHON_PROJECT_VERSION: $PYTHON_PROJECT_VERSION"

        # Make available in the environment
        echo "python_project_version=$PYTHON_PROJECT_VERSION" >> "$GITHUB_ENV"
        echo "python_project_version=$PYTHON_PROJECT_VERSION" >> "$GITHUB_OUTPUT"

        #SHELLCODEEND
