---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🏷️ Development Semantic Tag"

inputs:
  TAG:
    description: "The existing semantic tag to be incremented"
    required: false
  TYPE:
    description: "Increment to perform [major|minor|patch]"
    required: false
    default: "patch"

outputs:
  TAG:
    # A leading non-numeric "v" character will be stripped
    description: "The incremented semantic tag [purely numeric] e.g. 1.2.3"
    value: ${{ steps.increment.outputs.tag }}
  VTAG:
    # A leading non-numeric "v" character will be stripped
    description: "The incremented semantic tag [with prefix] e.g. v1.2.3"
    value: ${{ steps.increment.outputs.tag }}

  ### Return additional values NOT actually generated here
  # Convenience, prevents a separate call to: repository-tags-fetch
  CURRENT_TAG:
    description: "The existing semantic tag to be incremented, same as input"
    value: ${{ steps.increment.outputs.current_tag }}
  CURRENT_VTAG:
    description: "The existing semantic tag to be incremented, same as input"
    value: ${{ steps.increment.outputs.current_vtag }}

runs:
  using: "composite"
  steps:
    - name: "Enumerate current tag"
      id: current-tag
      uses: os-climate/osc-github-devops/.github/actions/repository-tags-fetch@main

    - name: "Create development tag"
      id: increment
      shell: bash
      run: |
        # Create development tag

        #SHELLCODESTART

        # Development tags will have date and time of build appended
        DATETIME=$(date +'%Y%m%d-%H%M')

        TAG=${{ inputs.TAG }}
        TYPE=${{ inputs.TYPE }}
        if [ -z "$TAG" ] && [ -z "$TYPE" ]; then
          echo "Running from shell script outside GitHub"
          if [ $# -ne 2 ]; then
            echo "Usage:  $0 [tag] [increment-type]"; exit 1
          else
            TAG="$1"
            TYPE="$2"
          fi
        fi

        # Validate increment type
        if	[ ! "$TYPE" = "major" ] && \
            [ ! "$TYPE" = "minor" ] && \
            [ ! "$TYPE" = "patch" ]; then
           echo "Increment type invalid"; exit 1
        fi

        # If tag was NOT supplied, get the current one from the repository
        if [ -z $TAG ]; then
          TAG=${{ steps.current-tag.outputs.vtag }}
        fi

        echo "Input tag: $TAG"
        echo "Increment type: $TYPE"

        # If present, strip the leading "v" character
        if [[ "$TAG" == v* ]]; then
          TAG="${TAG:1}"
        fi

        # Regular expression to match semantic tag
        PATTERN="^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$"

        # Validate supplied (and parsed) tag
        if ! [[ "$TAG" =~ $PATTERN ]]; then
          echo "ERROR: invalid semantic tag"; exit 1
        else
          echo "Numeric value: $TAG"
        fi

        REGEX='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
        MAJOR=$(echo "$TAG" | sed -e "s#$REGEX#\1#")
        MINOR=$(echo "$TAG" | sed -e "s#$REGEX#\2#")
        PATCH=$(echo "$TAG" | sed -e "s#$REGEX#\3#")
        echo "Current versioning [ major: $MAJOR  minor: $MINOR  patch: $PATCH ]"

        case "$TYPE" in
          major)
            MAJOR=$((MAJOR+1))
            MINOR="0"
            PATCH="0"
            ;;
          minor)
            MINOR=$((MINOR+1))
            PATCH="0"
            ;;
          patch)
            PATCH=$((PATCH+1))
            ;;
        esac

        # Note: Development suffic appended to regular tag/value
        TAG="$MAJOR.$MINOR.$PATCH-dev.$DATETIME"
        echo "Development tag: $TAG [v$TAG]"

        # Allows for testing from a local shell
        if [ -n "$GITHUB_OUTPUT" ]; then
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "vtag=v${TAG}" >> $GITHUB_OUTPUT
          echo "current_tag=${{ steps.current-tag.outputs.tag }} >> $GITHUB_OUTPUT
          echo "current_vtag=${{ steps.current-tag.outputs.vtag }} >> $GITHUB_OUTPUT
        fi

        #SHELLCODEEND
