---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "ðŸ› ï¸ GitHub Repository Metadata"
description: "Get GitHub Organisation and Repository Names"

outputs:
  OWNER:
    description: "Returns the name of the GitHub organisation"
    value: ${{ steps.github.outputs.organisation }}
  REPOSITORY:
    description: "Returns the name of the GitHub repository"
    value: ${{ steps.github.outputs.repository }}
  TAGGED:
    description: "Set true if semantic tags are present"
    value: ${{ steps.github.outputs.tagged }}

runs:
  using: "composite"
  steps:
    - name: "GitHub Repository Metadata"
      id: github
      shell: bash
      run: |
        # GitHub Repository Metadata
        TAGGED="false"
        echo "tagged=${TAGGED}" >> $GITHUB_OUTPUT

        echo "GitHub Owner: $GITHUB_REPOSITORY_OWNER"
        echo "owner=${GITHUB_REPOSITORY_OWNER}" >> "$GITHUB_OUTPUT"

        REPOSITORY=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
        echo "GitHub Repository: ${REPOSITORY}"
        echo "repository=${REPOSITORY}" >> "$GITHUB_OUTPUT"

        echo "### Action/Workflow Environment ###"
        if [ ! -z "$GITHUB_REF" ]; then
          echo "GITHUB_REF: $GITHUB_REF"
        fi
        if [ ! -z "$GITHUB_BASE_REF" ]; then
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
        fi
        if [ ! -z "$GITHUB_HEAD_REF" ]; then
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        fi
        if [ ! -z "$GITHUB_REF_NAME" ]; then
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          if [[ "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+ ]]; then
            echo "tagged=${TAGGED}" >> $GITHUB_OUTPUT
          fi
        fi
        if [ ! -z "$GITHUB_REF_TYPE" ]; then
          echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
        fi
        if [ ! -z "$GITHUB_EVENT_NAME" ]; then
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
        fi
        echo "GitHub event contained tags: $TAGGED"
