---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🔤 String Comparison Check"

inputs:
  STRING_A:
    description: "First string for comparison"
    required: true
  STRING_B:
    description: "Second string for comparison"
    required: true
  SUBSTRING_MATCH:
    description: "Match if string A contains string B"
    required: false
    default: "false"
  CASE_INSENSITIVE:
    required: false
    default: "false"

outputs:
  MATCH:
    description: "True if string matches based on provided inputs/parameters"
    value: ${{ steps.compare.outputs.match }}

runs:
  using: "composite"
  env: SUBSTRING_MATCH
  steps:
    - name: "Perform comparison of string values"
      id: compare
      shell: bash
      run: |
        # Perform comparison of string values

        #SHELLCODESTART

        # Allows for testing from a local shell
        if [ -z "$GITHUB_OUTPUT" ]; then
          echo "Running from a shell, NOT workflow"
          export GITHUB_OUTPUT="/dev/null"
        else
          STRING_A="${{ inputs.STRING_A }}"
          STRING_B="${{ inputs.STRING_B }}"
        fi

        if [ -z "$STRING_A" ]; then
          echo "Running from shell script outside GitHub"
          if [ $# -ne 2 ]; then
            echo "Usage:  $0 [first string] [second string]"; exit 1
          else
            STRING_A="$1"
            STRING_B="$2"
          fi
        fi

        if [ "$CASE_INSENSITIVE" = "true" ]; then
          echo "Case-insensitive string comparison requested"
          shopt -s nocasematch
        fi

        echo "First string: $STRING_A"
        echo "Second string: $STRING_B"

        # Check if string A contains string B
        if [[ "$SUBSTRING_MATCH" == "true" ]]; then
          echo "Sub-string match requested"
          if [[ "$STRING_A" =~ "$STRING_B" ]]; then
            echo "String A contains string B"
            MATCH="true"
          else
            echo "String A does NOT contain string B"
            MATCH="false"
          fi
        # Check for an exact match between strings
        else
          if [[ "$STRING_A" == "$STRING_B" ]]; then
            echo "Strings match"
            MATCH="true"
          else
            echo "Strings do NOT match"
            MATCH="false"
          fi
        fi

        # Allows for testing from a local shell
        if [ -n "$GITHUB_OUTPUT" ]; then
          echo "match=$MATCH" >> $GITHUB_OUTPUT
        fi

        #SHELLCODEEND
