---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "ðŸ·ï¸ Latest Semantic Tag"

outputs:
  tag:
    description: "Return the latest semantic tag from repository"
    value: ${{ steps.parse-tags.outputs.tag }}
  missing:
    description: "Flag set true if no semantic tags found"
    value: ${{ steps.parse-tags.outputs.missing }}

runs:
  using: "composite"
  steps:
    - name: "Report GitHub workflow environment"
      id: capture-environment
      shell: bash
      run: |
        # Report GitHub workflow environment
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "ref-parse-tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        # Report GitHub workflow environment
        echo "Github github.ref_name: ${{ github.ref_name }}"
        echo "Github github.head_ref: ${{ github.head_ref }}"
        echo "Github tag from GITHUB_REF: $RELEASE_VERSION"
        echo "Github workspace: ${{ github.workspace }}"
        echo "Github workspace: $GITHUB_WORKSPACE"

    - name: "Validate previous step outputs"
      id: report-environment
      shell: bash
      env:
        RELEASE_VERSION: ${{ steps.environment.outputs.ref-parse-tag }}
      run: |
        # Validate previous step outputs
        echo "Release version: $RELEASE_VERSION"
        echo ${{ steps.vars.outputs.ref-parse-tag }}

    - name: "ðŸ·ï¸ Parse tags"
      id: parse-tags
      shell: bash
      run: |
        GIT_CMD=$(which git)
        if [ -z "${GIT_CMD}" ]; then
          echo "Installing GIT command"
          apt-get -y update
          apt-get -y install git
        fi
        pwd
        cd ${{ github.workspace }}
        pwd
        #Â Extract and report latest semantic tag
        if ! (git tag -l | grep 'v*.*.*'); then
          echo "No semantic tags were found"
          echo "missing=true" >> $GITHUB_OUTPUT
          echo "tag=v0.0.0" >> $GITHUB_OUTPUT
        fi
        tag=$(git tag -l --sort=committerdate | grep -o 'v*.*.*' | sort -r | head -1)
        echo "missing=false" >> $GITHUB_OUTPUT
        echo "tag=${tag}" >> $GITHUB_OUTPUT
