---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "ðŸ·ï¸ Latest Semantic Tag"

outputs:
  TAG:
    description: "Return the latest semantic tag from local repository"
    value: ${{ steps.parse-tags.outputs.tag }}
  GITHUB-REF-NAME:
    description: "Returns workflow github.ref_name"
    value: ${{ github.ref_name }}
  GITHUB-HEAD-REF:
    description: "Returns workflow github.head_ref"
    value: ${{ github.head_ref }}

runs:
  using: "composite"
  steps:
    - id: parse-tags
      name: "Determine latest semantic tag"
      shell: bash
      run: |
        tag=$(git tag -l --sort=committerdate | grep -o 'v.*' | sort -r | head -1)
        echo "tag=$tag" >> "$GITHUB_OUTPUT"
        echo "Latest semantic tag = $tag"
        github-ref-name=${{ github.ref_name }}
        echo "github-ref-name=$github-ref-name" >> "$GITHUB_OUTPUT"
        echo "Github github.ref_name: $github-ref-name"
        github-head-ref=${{ github.head_ref }}
        echo "github-head-ref=$github-head-ref" >> "$GITHUB_OUTPUT"
        echo "Github github.head_ref: $github-head-ref"
