---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "ðŸ·ï¸ Latest Semantic Tag"

outputs:
  LATEST-TAG:
    description: "Return the latest semantic tag from local repository"
    value: ${{ steps.parse-tags.outputs.tag }}

runs:
  using: "composite"
  steps:
    - id: parse-tags
      name: "Determine latest semantic tag"
      shell: bash
      run: |
        LATEST_TAG=$(git tag -l --sort=committerdate | grep -o 'v.*' | sort -r | head -1)
        echo "latest-tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
        echo "Latest semantic tag = $LATEST_TAG"
        echo "github.ref_name: ${{ github.ref_name }}"
        echo "github.head_ref: ${{ github.head_ref }}"
