---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "ðŸ·ï¸ Latest Semantic Tag"

outputs:
  tag:
    description: "Return the latest semantic tag from repository"
    value: ${{ steps.parse-tags.outputs.tag }}
  missing:
    description: "Flag set true if no semantic tags found"
    value: ${{ steps.parse-tags.outputs.missing }}

runs:
  using: "composite"
  steps:
    - name: "ðŸŒ¦ï¸ Report GitHub environment"
      id: capture-environment
      shell: bash
      run: |
        # Report GitHub workflow environment
        echo "Github github.ref_name: ${{ github.ref_name }}"
        echo "Github github.head_ref: ${{ github.head_ref }}"

    #Â Workaround for: https://github.com/actions/checkout/issues/1471
    - name: "ðŸ·ï¸ Fetch tags"
      shell: bash
      run: |
        #Â Workaround for: https://github.com/actions/checkout/issues/1471
        echo "Fetching tags..."
        git fetch --tags
        echo "Listing tags:"
        git tag -l

    - name: "ðŸ·ï¸ Parse tags"
      id: parse-tags
      shell: bash
      run: |
        #Â Workaround for: https://github.com/actions/checkout/issues/1471
        echo "Fetching tags..."
        git fetch --tags
        echo "Listing tags:"
        git tag -l

        #Â Extract and report latest semantic tag
        echo "Parsing tags..."
        if ! (git tag -l | grep 'v*.*.*'); then
          echo "No semantic tags were found"
          echo "missing=true" >> $GITHUB_OUTPUT
          echo "tag=v0.0.0" >> $GITHUB_OUTPUT
        fi
        tag=$(git tag -l --sort=committerdate | grep -o 'v*.*.*' | sort -r | head -1)
        echo "missing=false" >> $GITHUB_OUTPUT
        echo "tag=${tag}" >> $GITHUB_OUTPUT
        echo "Latest tag: $tag"
