---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🔍 Classify Repository Content"
description: "Scans repository content and identifies further actions"

outputs:
  PYTHON:
    description: "Repository contains a Python project using pyproject.toml"
    value: ${{ steps.classification.outputs.python }}
  NOTEBOOKS:
    description: "Repository contains Python Jupyter Notebooks"
    value: ${{ steps.classification.outputs.notebooks }}
  TOX:
    description: "Repository contains a TOX condfigutation"
    value: ${{ steps.classification.outputs.tox }}

runs:
  using: "composite"
  steps:
    - name: "Check content, set output variables"
      id: classification
      shell: bash
      run: |
        # Check content, set output variables

        #SHELLCODESTART

        if [ -f pyproject.toml ]; then
          echo "Python project metadata found"
          echo "python=true" >> "$GITHUB_OUTPUT"
        else
          echo "python=false" >> "$GITHUB_OUTPUT"
        fi

        if [ -f tox.ini ]; then
          echo "TOX configuration found"
          echo "tox=true" >> "$GITHUB_OUTPUT"
        else
          echo "tox=false" >> "$GITHUB_OUTPUT"
        fi

        # Check if repository contains Jupyter Notebooks
        NOTEBOOKS=$(find . -name '*.ipynb' | wc -l )
        if [ "$NOTEBOOKS" -ne 0 ]; then
          echo "Jupyter notebooks found"
          echo "notebooks=true" >> "$GITHUB_OUTPUT"
        else
          echo "notebooks=false" >> "$GITHUB_OUTPUT"
        fi

        #SHELLCODEEND
