---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🐍 Patch Python Project Metadata/Version"

inputs:
  CURRENT:
    description: "Current version to replace"
    required: true
  TARGET:
    description: "Target/replacement version"
    required: true

runs:
  using: "composite"
  steps:
    - id: patch-pyproject-toml
      name: "Substituting project version string"
      shell: bash
      run: |
        # Substituting project version string
        FILEMATCH=$(grep "version = \"$CURRENT\"" pyproject.toml)
        if [ "$FILEMATCH" == "pyproject.toml" ]; then
          sed -i "s:version = \"$CURRENT\":version = \"$TARGET\":" pyproject.toml
        else
          echo "Error: specified version string $CURRENT was NOT found in pyproject.toml"
          exit 1
        fi
