---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🐍 Patch Python Project Metadata/Version"

inputs:
  CURRENT:
    description: "Current version to replace"
    required: true
    type: string
  TARGET:
    description: "Target/replacement version"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - id: patch-pyproject-toml
      name: "Substituting project version string"
      shell: bash
      run: |
        # Substituting project version string

        #SHELLCODESTART

        # Allows for testing from a local shell
        if [ -z "$GITHUB_OUTPUT" ]; then
          echo "Running from a shell, NOT workflow"
          export GITHUB_OUTPUT="/dev/null"
          export GITHUB_ENV="/dev/null"
          if [ $# -ne 2 ]; then
            echo "Error: invalid arguments specified"
            echo "Usage:  $0 [current-tag] [target-tag]"; exit 1
          else
            CURRENT="$1"
            TARGET="$2"
          fi
        else
          CURRENT=${{ inputs.CURRENT }}
          TARGET=${{ inputs.TARGET }}
        fi

        if [ -z "$CURRENT" ] || [ -z "$TARGET" ]; then
          echo "Error: one or more required inputs NOT received"
          echo "Check the calling workflow syntax and setup..."; exit 1
        fi

        # Attempt version string substitution for project
        sed -i -E "s:^version =.*$:version = \"$TARGET\":" pyproject.toml

        # Check to see if the above succeeded
        if !(grep -q "version = \"$TARGET\"" pyproject.toml); then
          echo "Error: failed version substitution in pyproject.toml"; exit 1
        fi

        #SHELLCODEEND
