---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "ðŸ› ï¸ Gather Workflow Metadata"
description: "Populates Variables with GitHub Repository/Workflow Metadata"

outputs:
  OWNER:
    description: "Returns the name of the GitHub organisation"
    value: ${{ steps.github.outputs.organisation }}
  REPOSITORY:
    description: "Returns the name of the GitHub repository"
    value: ${{ steps.github.outputs.repository }}
  TAGPUSH:
    description: "Set true if semantic tags were an event/trigger"
    value: ${{ steps.github.outputs.tagpush }}

runs:
  using: "composite"
  steps:
    # - name: "GitHub Repository Metadata"
    - id: github
      shell: bash
      run: |
        # GitHub Repository Metadata
        TAGPUSH="false"
        echo "tagpush=${TAGPUSH}" >> $GITHUB_OUTPUT

        echo "### Repository Data ###"
        echo "GitHub Owner: $GITHUB_REPOSITORY_OWNER"
        echo "owner=${GITHUB_REPOSITORY_OWNER}" >> "$GITHUB_OUTPUT"
        REPOSITORY=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
        echo "GitHub Repository: ${REPOSITORY}"
        echo "repository=${REPOSITORY}" >> "$GITHUB_OUTPUT"

        if [ ! -z "$GITHUB_TRIGGERING_ACTOR" ]; then
          echo "### User Data ###"
          echo "User responsible: $GITHUB_TRIGGERING_ACTOR [GITHUB_TRIGGERING_ACTOR]"
        fi

        echo "### Action/Workflow Environment ###"
        if [ ! -z "$GITHUB_REF" ]; then
          echo "GITHUB_REF: $GITHUB_REF"
        fi
        if [ ! -z "$GITHUB_BASE_REF" ]; then
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
        fi
        if [ ! -z "$GITHUB_HEAD_REF" ]; then
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        fi
        if [ ! -z "$GITHUB_REF_NAME" ]; then
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          if [[ "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+ ]]; then
            echo "tagpush=${TAGPUSH}" >> $GITHUB_OUTPUT
          fi
        fi
        if [ ! -z "$GITHUB_REF_TYPE" ]; then
          echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
        fi
        if [ ! -z "$GITHUB_EVENT_NAME" ]; then
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
        fi

        echo "### Derived Data ###
        echo "GitHub event/triggered by tags: $TAGPUSH"
