---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "Python Project Name"
description: "Returns the name of the Python Project"

outputs:
  PYTHON_PROJECT_NAME:
    description: "The name of the Python project from pyproject.toml"
    value: ${{ steps.python-project-name.outputs.python_project_name }}

runs:
  using: "composite"
  steps:
    - name: "Capture Python project name"
      id: python-project-name
      shell: bash
      run: |
        # Capture Python project name

        #SHELLCODESTART

        # Allows for testing from a local shell
        if [ -z "$GITHUB_OUTPUT" ]; then
          echo "Running from a shell, NOT workflow"
          export GITHUB_OUTPUT="/dev/null"
          export GITHUB_ENV="/dev/null"
        fi

        if [ -f pyproject.toml ]; then
          PYTHON_PROJECT_NAME=$(grep -E '^name = ".*"$' pyproject.toml | awk '{print $3}' | sed 's:"::g')
        fi

        # ToDo: get project name from other files
        #elif [ -f setup.py ]; then
        #  PYTHON_PROJECT_NAME=$(grep -E '^name = ".*"$' setup.py | awk '{print $3}' | sed 's:"::g')
        #else
        #  echo "Error: neither pyproject.toml not setup.py was found"; exit 1
        # fi
        echo "PYTHON_PROJECT_NAME: $PYTHON_PROJECT_NAME"

        # Make available in the environment
        echo "python_project_name=$PYTHON_PROJECT_NAME" >> "$GITHUB_ENV"
        echo "python_project_name=$PYTHON_PROJECT_NAME" >> "$GITHUB_OUTPUT"

        #SHELLCODEEND
