---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "📦 Release to GitHub"
# Packages a development/production release on GitHub"

on:
  workflow_call:
    inputs:
      PRERELEASE:
        description: "Mark release as pre-release version"
        type: boolean
        required: true
      TAG:
        # Tag to use for release/build name
        description: "Semantic tag for release/build"
        type: string
        required: true

jobs:
  github-release:
    name: "GitHub Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "⬇ Download build artefacts"
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.ref_name }}
          path: ${{ env.BUILD_ARTEFACTS }}

      - name: "DEVELOPMENT artefacts"
        uses: softprops/action-gh-release@v2
        if: env.GITHUB_RELEASE_ALWAYS
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ inputs.PRERELEASE }}
          # ToDo: DO WE WANT A DATE/TIME STAMP HERE?
          tag_name: ${{ inputs.tag }}
          name: "Development/build: ${{ inputs.tag }}"
          # body_path: ${{ github.workspace }}/CHANGELOG.rst
          files: |
            ${{ env.BUILD_ARTEFACTS }}/*.tar.gz
            ${{ env.BUILD_ARTEFACTS }}/*.whl
            ${{ env.BUILD_ARTEFACTS }}/*.sigstore*

      - name: "PRODUCTION artefacts"
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ inputs.PRERELEASE }}
          # ToDo: DO WE WANT A DATE/TIME STAMP HERE?
          tag_name: ${{ inputs.tag }}
          name: "Release/build: ${{ inputs.tag }}"
          # body_path: ${{ github.workspace }}/CHANGELOG.rst
          files: |
            ${{ env.BUILD_ARTEFACTS }}/*.tar.gz
            ${{ env.BUILD_ARTEFACTS }}/*.whl
            ${{ env.BUILD_ARTEFACTS }}/*.sigstore*
