---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "📦 Release to GitHub"
# Packages a development/production release on GitHub"

on:
  workflow_call:
    inputs:
      PRERELEASE:
        description: "Mark release as pre-release/development version"
        type: boolean
        required: false
        default: false
      TAG:
        # Force use of this tag/name for release
        description: "Semantic tag for release/build"
        type: string
        required: false
        default: ${{ needs.tagging.outputs.dev_tag }}

# Two release types supported, based on conditions

### Development Release
# github.event.pull_request.merged == true &&
# startsWith(github.ref, 'refs/tags/') != 'true'
# tag: ${{ needs.tagging.outputs.dev_tag }}

### Production Release
# On merge of tag push, create a production release
# if: github.event.pull_request.merged == true && startsWith(github.ref, 'refs/tags/')
# tag: ${{ github.ref_name }}

jobs:
  github-release:
    name: "GitHub Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    env:
      tag: ${{ github.event.inputs.tag }}
    steps:
      - name: "⬇ Download build artefacts"
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.ref_name }}
          path: ${{ env.BUILD_ARTEFACTS }}

      - name: "DEVELOPMENT release"
        uses: softprops/action-gh-release@v2
        if: ${{ inputs.PRERELEASE}}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ inputs.PRERELEASE }}
          # ToDo: DO WE WANT A DATE/TIME STAMP HERE?
          tag_name: ${{ inputs.tag }}
          name: "Development/build: ${{ inputs.tag }}"
          # body_path: ${{ github.workspace }}/CHANGELOG.rst
          files: |
            ${{ env.BUILD_ARTEFACTS }}/*.tar.gz
            ${{ env.BUILD_ARTEFACTS }}/*.whl
            ${{ env.BUILD_ARTEFACTS }}/*.sigstore*

      - name: "Check version string in pyproject.toml matches tag push"
        shell: bash
        run: |
          echo "ToDo: NOT IMPLEMENTED YET"

      - name: "PRODUCTION Release"
        uses: softprops/action-gh-release@v2
        if:
          # Run production release on merge of tag push
          github.event.pull_request.merged == true &&
          startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ inputs.PRERELEASE }}
          # ToDo: DO WE WANT A DATE/TIME STAMP HERE?
          tag_name: ${{ inputs.tag }}
          name: "Release/build: ${{ inputs.tag }}"
          # body_path: ${{ github.workspace }}/CHANGELOG.rst
          files: |
            ${{ env.BUILD_ARTEFACTS }}/*.tar.gz
            ${{ env.BUILD_ARTEFACTS }}/*.whl
            ${{ env.BUILD_ARTEFACTS }}/*.sigstore*
