---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🧪 Test (Matrix)"
# Runs tests on a Python project for a number of specified Python versions"

on:
  workflow_call:
    inputs:
      PYTHON-VERSION:
        # Usually specified/extracted from the file: pyproject.toml
        description: "Python matrix versions to use for test builds (in JSON)"
        required: true
        type: string

jobs:
  python-test-matrix:
    name: "Python Test (Matrix)"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python ${{ inputs.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: "Install PDM tooling"
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: "Test Python project"
        id: python-project-tests
        uses: os-climate/osc-github-devops/.github/actions/python-test-project@main
        with:
          python-version: ${{ inputs.python-version }}
